code --install-extension alefragnani.project-manager
code --install-extension antfu.file-nesting
code --install-extension bierner.docs-view
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension daylerees.rainglow
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-chat
code --install-extension Gruntfuggly.todo-tree
code --install-extension lokalise.i18n-ally
code --install-extension mattpocock.ts-error-translator
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mhutchie.git-graph
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension pomber.git-file-history
code --install-extension rust-lang.rust-analyzer
code --install-extension tamasfe.even-better-toml
code --install-extension tauri-apps.tauri-vscode
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension withfig.fig
code --install-extension wix.vscode-import-cost
code --install-extension yoavbls.pretty-ts-errors
