code --install-extension alefragnani.project-manager
code --install-extension bierner.docs-view
code --install-extension BriteSnow.vscode-toggle-quotes
code --install-extension daylerees.rainglow
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension GitHub.copilot
code --install-extension GitHub.copilot-labs
code --install-extension GitLab.gitlab-workflow
code --install-extension Gruntfuggly.todo-tree
code --install-extension imperez.smarty
code --install-extension johnpapa.vscode-peacock
code --install-extension lokalise.i18n-ally
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension matklad.rust-analyzer
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mhutchie.git-graph
code --install-extension ms-vscode.vscode-typescript-next
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension ms-vsliveshare.vsliveshare-pack
code --install-extension pnp.polacode
code --install-extension tamasfe.even-better-toml
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension wix.vscode-import-cost
code --install-extension wmaurer.vscode-jumpy
