# directories options
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT
setopt PUSHD_TO_HOME

# history
HISTSIZE=9999
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_SAVE_NO_DUPS
setopt INC_APPEND_HISTORY

# I/O
unsetopt CLOBBER # so we can '>' to truncate existing file

# globbing
setopt EXTENDED_GLOB

# scripts
setopt MULTIOS # so we can: `$ echo 'foo' > file1 > file2`

# zle
bindkey -e
bindkey "^[^[[D" backward-word         # alt-left
bindkey "^[^[[C" forward-word          # alt-right
bindkey "^[^?" backward-kill-word      # alt-backspace

# aliases
alias grep="grep --color=auto"
alias less="less -R"
alias l="ls -1A"
alias ls="ls -FG"
alias ll="ls -lh"
alias la="ll -A"
alias sl="ls"
alias df="df -kh"

# safe
alias cp="cp -i"
alias ln="ln -i"
alias mv="mv -i"
alias rm="rm -i"

# prompt
setopt PROMPT_SUBST
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' use-simple true
zstyle ':vcs_info:*' stagedstr '✚'
zstyle ':vcs_info:*' unstagedstr '*'
zstyle ':vcs_info:git*' formats ' %b%u%c'
zstyle ':vcs_info:git*' actionformats ' %b|%a'
precmd() { vcs_info }
PROMPT='%c%F{242}${vcs_info_msg_0_}%f %(?.%F{blue}.%F{red})%#%f '
RPROMPT=''

if [[ -f $HOME/.github_token ]]; then
  export GITHUB_TOKEN=$(cat $HOME/.github_token)
fi

alias fuck='sudo $(history -p \!\!)'
alias git=hub
export PATH="$PATH:`yarn global bin`"
source "$HOME/dev/overblog/Docker/src/docker.sh"
